services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
        - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8018:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
    expose:
      - 6333
    volumes:
      - ./backend/qdrant_data:/qdrant/storage


networks:
  app-network:
    driver: bridge